name: Push Testing
on: push
jobs:
  run_push_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "10"
      - name: Install dependencies
        run: npm ci
      - name: Run lint 
        run: npm run lint
      - name: Run tests
        run: npx mocha --mode push --cleanup
